add posttest for mac and ubuntu

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -222,7 +222,7 @@ jobs:
           repository: dotenv/dotenvx
           short-description: ${{ github.event.repository.description }}
 
-  posttest:
+  posttest-ubuntu:
     needs: test
     if: ${{ !(startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')) }}
     runs-on: ubuntu-latest
@@ -243,5 +243,66 @@ jobs:
           echo $EXPECTED_VERSION
           if [ "$RELEASED_VERSION" != "$EXPECTED_VERSION" ]; then
             echo "posttest version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
+            exit 1
+          fi
+      - name: verify dotenvx run
+        run: |
+          echo "HELLO=Ubuntu" > .env
+          echo "console.log('Hello ' + process.env.HELLO)" > index.js
+          EXPECTED_MESSAGE=$(dotenvx run --quiet -- node index.js)
+          echo $EXPECTED_MESSAGE
+          if [ "$EXPECTED_MESSAGE" != "Hello Ubuntu" ]; then
+            echo "posttest dotenvx run failure: expected Hello Ubuntu, got $EXPECTED_MESSAGE"
+            exit 1
+          fi
+      - name: verify dotenvx get
+        run: |
+          echo "HELLO=Ubuntu" > .env
+          EXPECTED_VALUE=$(dotenvx get HELLO)
+          echo $EXPECTED_VALUE
+          if [ "$EXPECTED_VALUE" != "Ubuntu" ]; then
+            echo "posttest dotenvx get failure: expected Ubuntu, got $EXPECTED_VALUE"
+            exit 1
+          fi
+  posttest-mac:
+    needs: test
+    if: ${{ !(startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')) }}
+    runs-on: macos-latest
+    strategy:
+      fail-fast: true
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 16.x
+      - name: install dotenvx
+        run: brew install dotenvx/brew/dotenvx
+      - name: verify version
+        run: |
+          RELEASED_VERSION=$(dotenvx --version)
+          EXPECTED_VERSION=$(node -p "require('./package.json').version")
+          echo $RELEASED_VERSION
+          echo $EXPECTED_VERSION
+          if [ "$RELEASED_VERSION" != "$EXPECTED_VERSION" ]; then
+            echo "posttest version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
+            exit 1
+          fi
+      - name: verify dotenvx run
+        run: |
+          echo "HELLO=Ubuntu" > .env
+          echo "console.log('Hello ' + process.env.HELLO)" > index.js
+          EXPECTED_MESSAGE=$(dotenvx run --quiet -- node index.js)
+          echo $EXPECTED_MESSAGE
+          if [ "$EXPECTED_MESSAGE" != "Hello Ubuntu" ]; then
+            echo "posttest dotenvx run failure: expected Hello Ubuntu, got $EXPECTED_MESSAGE"
+            exit 1
+          fi
+      - name: verify dotenvx get
+        run: |
+          echo "HELLO=Ubuntu" > .env
+          EXPECTED_VALUE=$(dotenvx get HELLO)
+          echo $EXPECTED_VALUE
+          if [ "$EXPECTED_VALUE" != "Ubuntu" ]; then
+            echo "posttest dotenvx get failure: expected Ubuntu, got $EXPECTED_VALUE"
             exit 1
           fi
