test deployment in 5 minutes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,7 +30,7 @@ jobs:
       # GITHUB_ENV operates like a .env file
       - name: extract version
         run: |
-          VERSION=0.44.3
+          VERSION=0.44.2
           CLEAN_VERSION=${VERSION#v}
           echo "VERSION=$VERSION" >> $GITHUB_ENV
           echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
@@ -60,6 +60,20 @@ jobs:
           git commit -m "${{ env.VERSION }}" --allow-empty
           git tag "${{ env.VERSION }}" --force
           git push origin HEAD --tags --force
+      - name: wait for deployment
+        run: |
+          end=$((SECONDS+300))
+          while [ $SECONDS -lt $end ]; do
+            current_version=$(curl -s https://dotenvx.sh/VERSION)
+            if [ "$current_version" == "${{ env.CLEAN_VERSION }}" ]; then
+              echo "dotenvx.sh deployment successful with version $current_version"
+              exit 0
+            fi
+            echo "waiting for deployment..."
+            sleep 10
+          done
+          echo "[DEPLOYMENT_FAILED]: VERSION did not update to ${{ env.CLEAN_VERSION }} within 5 minutes"
+          exit 1
 
   # test-windows:
   #   runs-on: windows-latest
