add postrelease version check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -249,7 +249,7 @@ jobs:
           echo $RELEASED_VERSION
           echo $EXPECTED_VERSION
           if [ "$RELEASED_VERSION" != "$EXPECTED_VERSION" ]; then
-            echo "posttest version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
+            echo "postrelease version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
             exit 1
           fi
       - name: verify dotenvx run/get
@@ -259,13 +259,13 @@ jobs:
           EXPECTED_MESSAGE=$(dotenvx run --quiet -- node index.js)
           echo $EXPECTED_MESSAGE
           if [ "$EXPECTED_MESSAGE" != "Hello Ubuntu" ]; then
-            echo "posttest dotenvx run failure: expected Hello Ubuntu, got $EXPECTED_MESSAGE"
+            echo "postrelease dotenvx run failure: expected Hello Ubuntu, got $EXPECTED_MESSAGE"
             exit 1
           fi
           EXPECTED_VALUE=$(dotenvx get HELLO)
           echo $EXPECTED_VALUE
           if [ "$EXPECTED_VALUE" != "Ubuntu" ]; then
-            echo "posttest dotenvx get failure: expected Ubuntu, got $EXPECTED_VALUE"
+            echo "postrelease dotenvx get failure: expected Ubuntu, got $EXPECTED_VALUE"
             exit 1
           fi
   postrelease-mac:
@@ -289,7 +289,7 @@ jobs:
           echo $RELEASED_VERSION
           echo $EXPECTED_VERSION
           if [ "$RELEASED_VERSION" != "$EXPECTED_VERSION" ]; then
-            echo "posttest version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
+            echo "postrelease version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
             exit 1
           fi
       - name: verify dotenvx run/get
@@ -299,13 +299,13 @@ jobs:
           EXPECTED_MESSAGE=$(dotenvx run --quiet -- node index.js)
           echo $EXPECTED_MESSAGE
           if [ "$EXPECTED_MESSAGE" != "Hello Mac" ]; then
-            echo "posttest dotenvx run failure: expected Hello Mac, got $EXPECTED_MESSAGE"
+            echo "postrelease dotenvx run failure: expected Hello Mac, got $EXPECTED_MESSAGE"
             exit 1
           fi
           EXPECTED_VALUE=$(dotenvx get HELLO)
           echo $EXPECTED_VALUE
           if [ "$EXPECTED_VALUE" != "Mac" ]; then
-            echo "posttest dotenvx get failure: expected Mac, got $EXPECTED_VALUE"
+            echo "postrelease dotenvx get failure: expected Mac, got $EXPECTED_VALUE"
             exit 1
           fi
   postrelease-windows:
@@ -326,16 +326,11 @@ jobs:
           Expand-Archive -Path dotenvx-windows-x86_64.zip -DestinationPath .\dotenvx
       - name: verify version
         run: |
-          $versionOutput = .\dotenvx\bin\windows-x86_64\dotenvx.exe --version
-          Write-Output "dotenvx version: $versionOutput"
-        shell: pwsh
-        # run: |
-        #   RELEASED_VERSION=$(.\dotenvx\bin\windows-x86_64\dotenvx --version)
-        #   EXPECTED_VERSION=$(node -p "require('./package.json').version")
-        #   echo $RELEASED_VERSION
-        #   echo $EXPECTED_VERSION
-        #   if [ "$RELEASED_VERSION" != "$EXPECTED_VERSION" ]; then
-        #     echo "posttest version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
-        #     exit 1
-        #   fi
-
+          $RELEASED_VERSION = .\dotenvx\bin\windows-x86_64\dotenvx.exe --version
+          $EXPECTED_VERSION = node -p "require('./package.json').version"
+          Write-Output "released version: $RELEASED_VERSION"
+          Write-Output "expected version: $EXPECTED_VERSION"
+          if ($RELEASED_VERSION -ne $EXPECTED_VERSION) {
+            Write-Output "postrelease version mismatch: expected $EXPECTED_VERSION, got $RELEASED_VERSION"
+            exit 1
+          }
