CHANGELOG.md

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,73 +21,6 @@ jobs:
       - run: npm run testshell
       - run: npm audit --omit=dev
 
-  dotenvx-sh:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-    steps:
-      - uses: actions/checkout@v4
-      # GITHUB_ENV operates like a .env file
-      - name: extract version
-        run: |
-          VERSION=0.44.3
-          CLEAN_VERSION=${VERSION#v}
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
-
-      - name: update install.sh with VERSION
-        run: |
-          mkdir -p dist
-          mkdir -p dist2
-          sed "0,/^VERSION=\".*\"/s//VERSION=\"${{ env.CLEAN_VERSION }}\"/" install.sh > ./dist/install.sh
-          sed "0,/^VERSION=\".*\"/s//VERSION=\"${{ env.CLEAN_VERSION }}\"/" install.sh > ./dist2/install.sh
-      - name: checkout dotenvx/dotenvx.sh repo
-        uses: actions/checkout@v4
-        with:
-          repository: "dotenvx/dotenvx.sh"
-          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-          path: "dotenvx.sh"
-      - name: copy install.sh to dotenvx.sh repo
-        run: |
-          cp dist2/install.sh dotenvx.sh/install.sh
-          echo "${{ env.CLEAN_VERSION }}" > dotenvx.sh/VERSION
-      - name: commit and push
-        run: |
-          cd dotenvx.sh
-          git config --global user.name 'motdotenv'
-          git config --global user.email 'mot@dotenv.org'
-          git add .
-          git commit -m "${{ env.VERSION }}" --allow-empty
-          git tag "${{ env.VERSION }}" --force
-          git push origin HEAD --tags --force
-
-  confirm-dotenvx-sh:
-    needs: dotenvx-sh
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: true
-    steps:
-      - name: extract version
-        run: |
-          VERSION=0.44.3
-          CLEAN_VERSION=${VERSION#v}
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-          echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
-      - name: wait for deployment
-        run: |
-          end=$((SECONDS+300))
-          while [ $SECONDS -lt $end ]; do
-            current_version=$(curl -s -L https://dotenvx.sh/VERSION)
-            if [ "$current_version" == "${{ env.CLEAN_VERSION }}" ]; then
-              echo "dotenvx.sh deployment successful with version $current_version"
-              exit 0
-            fi
-            echo "waiting for deployment..."
-            sleep 10
-          done
-          echo "[DEPLOYMENT_FAILED]: VERSION did not update to ${{ env.CLEAN_VERSION }} within 5 minutes"
-          exit 1
-
   # test-windows:
   #   runs-on: windows-latest
   #   strategy:
@@ -473,8 +406,71 @@ jobs:
       - name: publish-all aggregate step
         run: echo "publish-all completed"
 
-  postrelease-ubuntu:
+  dotenvx-sh:
     needs: publish-all
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+    steps:
+      - uses: actions/checkout@v4
+      - name: extract version
+        run: |
+          VERSION=${GITHUB_REF#refs/tags/}
+          CLEAN_VERSION=${VERSION#v}
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
+      - name: update install.sh with VERSION
+        run: |
+          mkdir -p dist
+          sed "0,/^VERSION=\".*\"/s//VERSION=\"${{ env.CLEAN_VERSION }}\"/" install.sh > ./dist/install.sh
+      - name: checkout dotenvx/dotenvx.sh repo
+        uses: actions/checkout@v4
+        with:
+          repository: "dotenvx/dotenvx.sh"
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          path: "dotenvx.sh"
+      - name: copy install.sh to dotenvx.sh repo
+        run: |
+          cp dist/install.sh dotenvx.sh/install.sh
+          echo "${{ env.CLEAN_VERSION }}" > dotenvx.sh/VERSION
+      - name: commit and push
+        run: |
+          cd dotenvx.sh
+          git config --global user.name 'motdotenv'
+          git config --global user.email 'mot@dotenv.org'
+          git add .
+          git commit -m "${{ env.VERSION }}" --allow-empty
+          git tag "${{ env.VERSION }}" --force
+          git push origin HEAD --tags --force
+  confirm-dotenvx-sh:
+    needs: dotenvx-sh
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+    steps:
+      - name: extract version
+        run: |
+          VERSION=${GITHUB_REF#refs/tags/}
+          CLEAN_VERSION=${VERSION#v}
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+          echo "CLEAN_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
+      - name: wait for deployment
+        run: |
+          end=$((SECONDS+300))
+          while [ $SECONDS -lt $end ]; do
+            current_version=$(curl -s -L https://dotenvx.sh/VERSION)
+            if [ "$current_version" == "${{ env.CLEAN_VERSION }}" ]; then
+              echo "dotenvx.sh deployment successful with version $current_version"
+              exit 0
+            fi
+            echo "waiting for deployment..."
+            sleep 10
+          done
+          echo "[DEPLOYMENT_FAILED]: VERSION did not update to ${{ env.CLEAN_VERSION }} within 5 minutes"
+          exit 1
+
+  postrelease-ubuntu:
+    needs: confirm-dotenvx-sh
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
@@ -514,7 +510,7 @@ jobs:
             exit 1
           fi
   postrelease-mac:
-    needs: publish-all
+    needs: confirm-dotenvx-sh
     runs-on: macos-latest
     strategy:
       fail-fast: true
@@ -554,7 +550,7 @@ jobs:
             exit 1
           fi
   postrelease-windows:
-    needs: publish-all
+    needs: confirm-dotenvx-sh
     runs-on: windows-latest
     strategy:
       fail-fast: true
