move to postrelease

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,24 +57,6 @@ jobs:
       - run: npm install
       - run: npm run standard
       - run: npm run test-coverage
-  test-bunx:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-      - name: run test with bun image
-        run: |
-          docker run --rm \
-            -v $(pwd):/workspace \
-            -w /workspace \
-            oven/bun:1.1.25-alpine \
-            sh -c 'cd /workspace && npm install && bun ./src/cli/dotenvx.js run --env "HELLO=World" --overload -- sh -c "echo Hello $HELLO"' | tee output.txt
-          output=$(cat output.txt)
-          if [ "$output" != "Hello World" ]; then
-            echo "Test failed: $output"
-            exit 1
-          fi
-          echo "Test passed"
-
   # run only on semantic version tag
   release:
     needs: test
@@ -828,3 +810,27 @@ jobs:
             exit 1
           }
         shell: pwsh
+
+  postrelease-bunx:
+    #needs: confirm-dotenvx-sh
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 16.x
+      - name: run test with bun image
+        run: |
+          $EXPECTED_VERSION = node -p "require('./package.json').version"
+          docker run --rm \
+            -v $(pwd):/workspace \
+            -w /workspace \
+            oven/bun:1.1.25-alpine \
+            sh -c 'bunx @dotenvx/dotenvx@$EXPECTED_VERSION run --env "HELLO=Bun" --overload -- sh -c "echo Hello $HELLO"' | tee output.txt
+          output=$(cat output.txt)
+          if [ "$output" != "Hello Bun" ]; then
+            echo "postrelease dotenvx run failure: expected Hello Bun, got $output"
+            exit 1
+          fi
